-- Generated by backend/store/pgschema from the fully migrated combined
-- SQLite schema, including every plugin's migrations. Do not edit by hand:
-- TestBaselineMatchesSQLiteSchema regenerates this file and fails when it
-- differs, which is what keeps the PostgreSQL baseline honest while SQLite
-- migrations still land.
--
-- Type choices are documented in translate.go. In short: unix timestamps and
-- 0/1 booleans stay bigint, every text column is C-collated so ordering and
-- comparison keep the byte-wise semantics the store relies on, and identity
-- columns are GENERATED BY DEFAULT so the migration can copy ids verbatim.

-- table attachments
CREATE TABLE attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  blob_id bigint NOT NULL,
  filename text COLLATE "C" NOT NULL,
  content_type text COLLATE "C" NOT NULL,
  content_id text COLLATE "C" NOT NULL DEFAULT '',
  is_inline bigint NOT NULL DEFAULT 0,
  size bigint NOT NULL,
  blob_path text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL
);

-- table blob_cleanup_queue
CREATE TABLE blob_cleanup_queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  blob_id bigint NOT NULL,
  blob_path text COLLATE "C" NOT NULL,
  blob_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  blob_size bigint NOT NULL DEFAULT 0,
  blob_created_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, blob_id)
);

-- table blobs
CREATE TABLE blobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  kind text COLLATE "C" NOT NULL,
  path text COLLATE "C" NOT NULL,
  sha256 text COLLATE "C" NOT NULL,
  size bigint NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE(user_id, path)
);

-- table calendar_events
CREATE TABLE calendar_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  calendar_id bigint NOT NULL,
  external_id text COLLATE "C" NOT NULL,
  etag text COLLATE "C" NOT NULL DEFAULT '',
  ical_uid text COLLATE "C" NOT NULL DEFAULT '',
  summary text COLLATE "C" NOT NULL DEFAULT '',
  description text COLLATE "C" NOT NULL DEFAULT '',
  location text COLLATE "C" NOT NULL DEFAULT '',
  status text COLLATE "C" NOT NULL DEFAULT '',
  start_at bigint NOT NULL DEFAULT 0,
  end_at bigint NOT NULL DEFAULT 0,
  all_day bigint NOT NULL DEFAULT 0,
  time_zone text COLLATE "C" NOT NULL DEFAULT '',
  recurring_event_id text COLLATE "C" NOT NULL DEFAULT '',
  organizer_email text COLLATE "C" NOT NULL DEFAULT '',
  organizer_name text COLLATE "C" NOT NULL DEFAULT '',
  attendees_json text COLLATE "C" NOT NULL DEFAULT '',
  my_response text COLLATE "C" NOT NULL DEFAULT '',
  html_link text COLLATE "C" NOT NULL DEFAULT '',
  remote_updated_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table calendars
CREATE TABLE calendars (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  google_connection_id bigint NOT NULL,
  google_calendar_id text COLLATE "C" NOT NULL,
  summary text COLLATE "C" NOT NULL DEFAULT '',
  description text COLLATE "C" NOT NULL DEFAULT '',
  time_zone text COLLATE "C" NOT NULL DEFAULT '',
  color text COLLATE "C" NOT NULL DEFAULT '',
  access_role text COLLATE "C" NOT NULL DEFAULT '',
  is_primary bigint NOT NULL DEFAULT 0,
  selected bigint NOT NULL DEFAULT 1,
  sync_token text COLLATE "C" NOT NULL DEFAULT '',
  window_start_at bigint NOT NULL DEFAULT 0,
  last_sync_at bigint NOT NULL DEFAULT 0,
  last_success_at bigint NOT NULL DEFAULT 0,
  status text COLLATE "C" NOT NULL DEFAULT '',
  status_detail text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table category_sender_overrides
CREATE TABLE category_sender_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  sender text COLLATE "C" NOT NULL,
  category text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, sender)
);

-- table contact_addresses
CREATE TABLE contact_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  street text COLLATE "C" NOT NULL DEFAULT '',
  locality text COLLATE "C" NOT NULL DEFAULT '',
  region text COLLATE "C" NOT NULL DEFAULT '',
  postal_code text COLLATE "C" NOT NULL DEFAULT '',
  country text COLLATE "C" NOT NULL DEFAULT '',
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table contact_emails
CREATE TABLE contact_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  email text COLLATE "C" NOT NULL,
  normalized_email text COLLATE "C" NOT NULL,
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  sort_order bigint NOT NULL DEFAULT 0
);

-- table contact_icons
CREATE TABLE contact_icons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  blob_id bigint NOT NULL,
  content_type text COLLATE "C" NOT NULL,
  filename text COLLATE "C" NOT NULL DEFAULT '',
  size bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, contact_id)
);

-- table contact_pgp_public_keys
CREATE TABLE contact_pgp_public_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  email text COLLATE "C" NOT NULL DEFAULT '',
  normalized_email text COLLATE "C" NOT NULL DEFAULT '',
  label text COLLATE "C" NOT NULL DEFAULT '',
  fingerprint text COLLATE "C" NOT NULL DEFAULT '',
  key_id text COLLATE "C" NOT NULL DEFAULT '',
  user_ids text COLLATE "C" NOT NULL DEFAULT '',
  public_key_armored text COLLATE "C" NOT NULL DEFAULT '',
  is_preferred bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  source_kind text COLLATE "C" NOT NULL DEFAULT 'manual',
  source_detail text COLLATE "C" NOT NULL DEFAULT ''
);

-- table contact_phones
CREATE TABLE contact_phones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  number text COLLATE "C" NOT NULL,
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table contact_urls
CREATE TABLE contact_urls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  url text COLLATE "C" NOT NULL,
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table contacts
CREATE TABLE contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name_prefix text COLLATE "C" NOT NULL DEFAULT '',
  given_name text COLLATE "C" NOT NULL DEFAULT '',
  additional_name text COLLATE "C" NOT NULL DEFAULT '',
  family_name text COLLATE "C" NOT NULL DEFAULT '',
  name_suffix text COLLATE "C" NOT NULL DEFAULT '',
  display_name text COLLATE "C" NOT NULL DEFAULT '',
  nickname text COLLATE "C" NOT NULL DEFAULT '',
  organization text COLLATE "C" NOT NULL DEFAULT '',
  department text COLLATE "C" NOT NULL DEFAULT '',
  job_title text COLLATE "C" NOT NULL DEFAULT '',
  birthday text COLLATE "C" NOT NULL DEFAULT '',
  notes text COLLATE "C" NOT NULL DEFAULT '',
  categories text COLLATE "C" NOT NULL DEFAULT '',
  is_me bigint NOT NULL DEFAULT 0,
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  source text COLLATE "C" NOT NULL DEFAULT 'local',
  google_connection_id bigint NOT NULL DEFAULT 0,
  external_id text COLLATE "C" NOT NULL DEFAULT '',
  etag text COLLATE "C" NOT NULL DEFAULT '',
  remote_updated_at bigint NOT NULL DEFAULT 0
);

-- table expunged_message_fingerprints
CREATE TABLE expunged_message_fingerprints (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  source_mailbox_id bigint NOT NULL,
  source_uid bigint NOT NULL DEFAULT 0,
  source_uid_validity bigint NOT NULL DEFAULT 0,
  raw_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  internal_date_unix bigint NOT NULL DEFAULT 0,
  message_size bigint NOT NULL DEFAULT 0,
  consumed_message_id bigint,
  created_at bigint NOT NULL,
  consumed_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL,
  UNIQUE(user_id, account_id, source_mailbox_id, source_uid, source_uid_validity)
);

-- table google_calendar_sync
CREATE TABLE google_calendar_sync (
  user_id bigint NOT NULL,
  connection_id bigint NOT NULL,
  sync_token text COLLATE "C" NOT NULL DEFAULT '',
  last_sync_at bigint NOT NULL DEFAULT 0,
  last_success_at bigint NOT NULL DEFAULT 0,
  status text COLLATE "C" NOT NULL DEFAULT '',
  status_detail text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, connection_id)
);

-- table google_connections
CREATE TABLE google_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  google_email text COLLATE "C" NOT NULL,
  google_subject text COLLATE "C" NOT NULL,
  encrypted_refresh_token text COLLATE "C" NOT NULL,
  encrypted_access_token text COLLATE "C" NOT NULL DEFAULT '',
  access_token_expires_at bigint NOT NULL DEFAULT 0,
  granted_scopes text COLLATE "C" NOT NULL DEFAULT '',
  status text COLLATE "C" NOT NULL DEFAULT 'ok',
  status_detail text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, google_subject)
);

-- table google_people_sync
CREATE TABLE google_people_sync (
  user_id bigint NOT NULL,
  connection_id bigint NOT NULL,
  sync_token text COLLATE "C" NOT NULL DEFAULT '',
  last_sync_at bigint NOT NULL DEFAULT 0,
  last_success_at bigint NOT NULL DEFAULT 0,
  status text COLLATE "C" NOT NULL DEFAULT '',
  status_detail text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, connection_id)
);

-- table identity_pgp_private_keys
CREATE TABLE identity_pgp_private_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  identity_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  fingerprint text COLLATE "C" NOT NULL DEFAULT '',
  key_id text COLLATE "C" NOT NULL DEFAULT '',
  user_ids text COLLATE "C" NOT NULL DEFAULT '',
  public_key_armored text COLLATE "C" NOT NULL DEFAULT '',
  encrypted_private_key text COLLATE "C" NOT NULL DEFAULT '',
  private_key_storage text COLLATE "C" NOT NULL DEFAULT 'server',
  revocation_certificate text COLLATE "C" NOT NULL DEFAULT '',
  is_active_signing bigint NOT NULL DEFAULT 0,
  is_active_encryption bigint NOT NULL DEFAULT 0,
  is_decrypt_only bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table locations
CREATE TABLE locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  uid bigint NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE(user_id, message_id, mailbox_id, uid)
);

-- table mail_accounts
CREATE TABLE mail_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  email text COLLATE "C" NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  host text COLLATE "C" NOT NULL,
  port bigint NOT NULL,
  username text COLLATE "C" NOT NULL,
  encrypted_password text COLLATE "C" NOT NULL,
  use_tls bigint NOT NULL DEFAULT 1,
  smtp_host text COLLATE "C" NOT NULL DEFAULT '',
  smtp_port bigint NOT NULL DEFAULT 587,
  smtp_username text COLLATE "C" NOT NULL DEFAULT '',
  encrypted_smtp_password text COLLATE "C" NOT NULL DEFAULT '',
  smtp_use_tls bigint NOT NULL DEFAULT 1,
  mailbox text COLLATE "C" NOT NULL DEFAULT 'INBOX',
  sync_interval_minutes bigint NOT NULL DEFAULT 15,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  auth_type text COLLATE "C" NOT NULL DEFAULT 'password',
  google_connection_id bigint NOT NULL DEFAULT 0,
  sync_start_at bigint NOT NULL DEFAULT 0
);

-- table mail_identities
CREATE TABLE mail_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  contact_email_id bigint NOT NULL,
  smtp_account_id bigint NOT NULL DEFAULT 0,
  email text COLLATE "C" NOT NULL,
  display_name text COLLATE "C" NOT NULL DEFAULT '',
  signature text COLLATE "C" NOT NULL DEFAULT '',
  is_primary bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  sent_mailbox_id bigint NOT NULL DEFAULT 0,
  drafts_mailbox_id bigint NOT NULL DEFAULT 0,
  imap_account_id bigint NOT NULL DEFAULT 0,
  autocrypt_enabled bigint NOT NULL DEFAULT 1,
  archive_mailbox_id bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, contact_email_id)
);

-- table mailbox_generation_blob_cleanup
CREATE TABLE mailbox_generation_blob_cleanup (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  target_uid_validity bigint NOT NULL,
  blob_id bigint NOT NULL,
  blob_path text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, blob_id)
);

-- table mailbox_generation_rebuild_inbox_arrivals
CREATE TABLE mailbox_generation_rebuild_inbox_arrivals (
  rebuild_message_id bigint NOT NULL,
  user_id bigint NOT NULL,
  original_arrival_id bigint NOT NULL,
  sync_run_id bigint,
  classification text COLLATE "C" NOT NULL CHECK (classification IN ('pending', 'delivery', 'local_move', 'local_copy', 'external_move')),
  raw_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  internal_date_unix bigint NOT NULL DEFAULT 0,
  message_size bigint NOT NULL DEFAULT 0,
  matched_transfer_id bigint NOT NULL DEFAULT 0,
  matched_expunged_id bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  available_at bigint NOT NULL,
  finalized_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL,
  PRIMARY KEY(user_id, original_arrival_id),
  UNIQUE(rebuild_message_id)
);

-- table mailbox_generation_rebuild_messages
CREATE TABLE mailbox_generation_rebuild_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  target_uid_validity bigint NOT NULL,
  source_message_id bigint NOT NULL,
  source_uid bigint NOT NULL,
  raw_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  internal_date_unix bigint NOT NULL DEFAULT 0,
  message_size bigint NOT NULL DEFAULT 0,
  is_read bigint NOT NULL DEFAULT 0,
  read_sync_pending bigint NOT NULL DEFAULT 0,
  is_starred bigint NOT NULL DEFAULT 0,
  star_sync_pending bigint NOT NULL DEFAULT 0,
  has_snooze bigint NOT NULL DEFAULT 0,
  snooze_id bigint NOT NULL DEFAULT 0,
  snooze_thread_key text COLLATE "C" NOT NULL DEFAULT '',
  snooze_generation bigint NOT NULL DEFAULT 0,
  snoozed_until bigint NOT NULL DEFAULT 0,
  snooze_reminded_at bigint NOT NULL DEFAULT 0,
  snooze_created_at bigint NOT NULL DEFAULT 0,
  snooze_updated_at bigint NOT NULL DEFAULT 0,
  has_new_mail_event bigint NOT NULL DEFAULT 0,
  new_mail_event_id bigint NOT NULL DEFAULT 0,
  new_mail_from_addr text COLLATE "C" NOT NULL DEFAULT '',
  new_mail_subject text COLLATE "C" NOT NULL DEFAULT '',
  new_mail_created_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, source_message_id)
);

-- table mailbox_generation_rebuild_snooze_events
CREATE TABLE mailbox_generation_rebuild_snooze_events (
  rebuild_message_id bigint NOT NULL,
  user_id bigint NOT NULL,
  original_event_id bigint NOT NULL,
  snooze_generation bigint NOT NULL,
  from_addr text COLLATE "C" NOT NULL DEFAULT '',
  subject text COLLATE "C" NOT NULL DEFAULT '',
  due_at bigint NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY(user_id, original_event_id)
);

-- table mailbox_generation_rebuild_unsubscribe_sends
CREATE TABLE mailbox_generation_rebuild_unsubscribe_sends (
  rebuild_message_id bigint NOT NULL,
  user_id bigint NOT NULL,
  original_send_id bigint NOT NULL,
  sender text COLLATE "C" NOT NULL DEFAULT '',
  unsubscribe_url text COLLATE "C" NOT NULL,
  sent_at bigint NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY(user_id, original_send_id)
);

-- table mailbox_generation_rebuilds
CREATE TABLE mailbox_generation_rebuilds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  target_uid_validity bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  arrival_uid_floor bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, account_id, mailbox_id)
);

-- table mailboxes
CREATE TABLE mailboxes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  name text COLLATE "C" NOT NULL,
  sync_mode text COLLATE "C" NOT NULL DEFAULT 'auto',
  role text COLLATE "C" NOT NULL DEFAULT '',
  icon text COLLATE "C" NOT NULL DEFAULT 'folder',
  show_in_sidebar bigint NOT NULL DEFAULT 1,
  show_in_all_mail bigint NOT NULL DEFAULT 1,
  include_in_search bigint NOT NULL DEFAULT 1,
  uidvalidity bigint NOT NULL DEFAULT 0,
  last_uid bigint NOT NULL DEFAULT 0,
  remote_message_count bigint NOT NULL DEFAULT 0,
  remote_unread_count bigint NOT NULL DEFAULT 0,
  remote_uid_next bigint NOT NULL DEFAULT 0,
  status_checked_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  search_index_purged bigint NOT NULL DEFAULT 0,
  search_index_state_known bigint NOT NULL DEFAULT 1,
  UNIQUE(user_id, account_id, name)
);

-- table message_snoozes
CREATE TABLE message_snoozes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  thread_key text COLLATE "C" NOT NULL,
  generation bigint NOT NULL DEFAULT 1,
  snoozed_until bigint NOT NULL,
  reminded_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, thread_key),
  UNIQUE(user_id, message_id)
);

-- table message_transfers
CREATE TABLE message_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  source_account_id bigint NOT NULL,
  destination_account_id bigint NOT NULL,
  source_mailbox_id bigint,
  destination_mailbox_id bigint NOT NULL,
  source_message_id bigint,
  source_uid bigint NOT NULL DEFAULT 0,
  source_uid_validity bigint NOT NULL DEFAULT 0,
  destination_uid bigint NOT NULL DEFAULT 0,
  destination_uid_validity bigint NOT NULL DEFAULT 0,
  operation_kind text COLLATE "C" NOT NULL CHECK (operation_kind IN ('move', 'copy')),
  state text COLLATE "C" NOT NULL CHECK (state IN ('pending', 'succeeded', 'failed', 'consumed')),
  raw_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  internal_date_unix bigint NOT NULL DEFAULT 0,
  message_size bigint NOT NULL DEFAULT 0,
  consumed_message_id bigint,
  legacy_marker_id bigint UNIQUE,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  dispatched_at bigint NOT NULL DEFAULT 0,
  completed_at bigint NOT NULL DEFAULT 0,
  consumed_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL,
  dispatch_owner text COLLATE "C" NOT NULL DEFAULT '',
  dispatch_attempt bigint NOT NULL DEFAULT 0,
  dispatch_finished_at bigint NOT NULL DEFAULT 0,
  destination_snapshot_uid_validity bigint NOT NULL DEFAULT 0,
  destination_snapshot_uid_next bigint NOT NULL DEFAULT 0
);

-- table messages
CREATE TABLE messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  blob_id bigint NOT NULL,
  message_id_header text COLLATE "C" NOT NULL DEFAULT '',
  in_reply_to text COLLATE "C" NOT NULL DEFAULT '',
  references_header text COLLATE "C" NOT NULL DEFAULT '',
  thread_key text COLLATE "C" NOT NULL DEFAULT '',
  thread_headers_checked_at bigint NOT NULL DEFAULT 0,
  subject text COLLATE "C" NOT NULL DEFAULT '',
  language_code text COLLATE "C" NOT NULL DEFAULT '',
  from_addr text COLLATE "C" NOT NULL DEFAULT '',
  to_addr text COLLATE "C" NOT NULL DEFAULT '',
  cc_addr text COLLATE "C" NOT NULL DEFAULT '',
  date_unix bigint NOT NULL DEFAULT 0,
  internal_date_unix bigint NOT NULL DEFAULT 0,
  uid bigint NOT NULL,
  size bigint NOT NULL DEFAULT 0,
  blob_path text COLLATE "C" NOT NULL,
  body_text text COLLATE "C" NOT NULL DEFAULT '',
  body_html text COLLATE "C" NOT NULL DEFAULT '',
  is_read bigint NOT NULL DEFAULT 0,
  read_sync_pending bigint NOT NULL DEFAULT 0,
  is_starred bigint NOT NULL DEFAULT 0,
  star_sync_pending bigint NOT NULL DEFAULT 0,
  has_attachments bigint NOT NULL DEFAULT 0,
  attachment_indexed_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  uid_validity bigint NOT NULL DEFAULT 0,
  import_completed_at bigint NOT NULL DEFAULT 0,
  duplicate_of_message_id bigint NOT NULL DEFAULT 0,
  category text COLLATE "C" NOT NULL DEFAULT '',
  sender_address text COLLATE "C" NOT NULL DEFAULT '',
  is_encrypted bigint NOT NULL DEFAULT 0,
  is_signed bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, account_id, mailbox_id, uid)
);

-- table new_mail_events
CREATE TABLE new_mail_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  from_addr text COLLATE "C" NOT NULL DEFAULT '',
  subject text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  UNIQUE(user_id, message_id)
);

-- table password_reset_tokens
CREATE TABLE password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token_hash text COLLATE "C" NOT NULL UNIQUE,
  expires_at bigint NOT NULL,
  used_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

-- table pending_inbox_arrivals
CREATE TABLE pending_inbox_arrivals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  message_id bigint NOT NULL,
  sync_run_id bigint,
  classification text COLLATE "C" NOT NULL CHECK (classification IN ('pending', 'delivery', 'local_move', 'local_copy', 'external_move')),
  raw_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  canonical_sha256 text COLLATE "C" NOT NULL DEFAULT '',
  message_id_hash text COLLATE "C" NOT NULL DEFAULT '',
  internal_date_unix bigint NOT NULL DEFAULT 0,
  message_size bigint NOT NULL DEFAULT 0,
  matched_transfer_id bigint NOT NULL DEFAULT 0,
  matched_expunged_id bigint NOT NULL DEFAULT 0,
  event_id bigint,
  created_at bigint NOT NULL,
  available_at bigint NOT NULL,
  finalized_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, message_id)
);

-- table pending_move_notifications
CREATE TABLE pending_move_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  destination_mailbox_id bigint NOT NULL,
  raw_sha256 text COLLATE "C" NOT NULL,
  consumed_message_id bigint,
  created_at bigint NOT NULL,
  consumed_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL
);

-- table plugin_bimi_brand_icons
CREATE TABLE plugin_bimi_brand_icons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  domain text COLLATE "C" NOT NULL,
  logo_url text COLLATE "C" NOT NULL DEFAULT '',
  svg text COLLATE "C" NOT NULL DEFAULT '',
  status text COLLATE "C" NOT NULL DEFAULT '',
  error text COLLATE "C" NOT NULL DEFAULT '',
  fetched_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, domain)
);

-- table plugin_experimental_spam_backfills
CREATE TABLE plugin_experimental_spam_backfills (
  user_id bigint PRIMARY KEY,
  model_version text COLLATE "C" NOT NULL DEFAULT '',
  status text COLLATE "C" NOT NULL CHECK (status IN ('idle', 'running', 'complete', 'failed', 'cancelled')),
  requested bigint NOT NULL DEFAULT 0,
  processed bigint NOT NULL DEFAULT 0,
  failed bigint NOT NULL DEFAULT 0,
  last_message_id bigint NOT NULL DEFAULT 0,
  last_error text COLLATE "C" NOT NULL DEFAULT '',
  started_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL,
  completed_at bigint NOT NULL DEFAULT 0
);

-- table plugin_experimental_spam_bayes_documents
CREATE TABLE plugin_experimental_spam_bayes_documents (
  user_id bigint NOT NULL,
  message_fingerprint bytea NOT NULL CHECK (length(message_fingerprint) = 32),
  token_schema text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, message_fingerprint)
);

-- table plugin_experimental_spam_bayes_labels
CREATE TABLE plugin_experimental_spam_bayes_labels (
  user_id bigint NOT NULL,
  message_fingerprint bytea NOT NULL CHECK (length(message_fingerprint) = 32),
  source text COLLATE "C" NOT NULL CHECK (source IN ('explicit', 'automatic')),
  origin_key text COLLATE "C" NOT NULL,
  message_id bigint,
  label text COLLATE "C" NOT NULL CHECK (label IN ('spam', 'ham')),
  token_schema text COLLATE "C" NOT NULL,
  learned_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, message_fingerprint, source, origin_key)
);

-- table plugin_experimental_spam_bayes_learn_tokens
CREATE TABLE plugin_experimental_spam_bayes_learn_tokens (
  user_id bigint NOT NULL,
  message_fingerprint bytea NOT NULL CHECK (length(message_fingerprint) = 32),
  token_hash bytea NOT NULL CHECK (length(token_hash) = 32),
  PRIMARY KEY (user_id, message_fingerprint, token_hash)
);

-- table plugin_experimental_spam_bayes_learns
CREATE TABLE plugin_experimental_spam_bayes_learns (
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  message_fingerprint bytea NOT NULL CHECK (length(message_fingerprint) = 32),
  label text COLLATE "C" NOT NULL CHECK (label IN ('spam', 'ham')),
  source text COLLATE "C" NOT NULL DEFAULT 'explicit' CHECK (source IN ('explicit', 'automatic')),
  token_schema text COLLATE "C" NOT NULL,
  learned_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, message_id)
);

-- table plugin_experimental_spam_bayes_state
CREATE TABLE plugin_experimental_spam_bayes_state (
  user_id bigint PRIMARY KEY,
  token_schema text COLLATE "C" NOT NULL,
  spam_messages bigint NOT NULL DEFAULT 0 CHECK (spam_messages >= 0),
  ham_messages bigint NOT NULL DEFAULT 0 CHECK (ham_messages >= 0),
  token_count bigint NOT NULL DEFAULT 0 CHECK (token_count >= 0),
  updated_at bigint NOT NULL
);

-- table plugin_experimental_spam_bayes_tokens
CREATE TABLE plugin_experimental_spam_bayes_tokens (
  user_id bigint NOT NULL,
  token_hash bytea NOT NULL CHECK (length(token_hash) = 32),
  spam_messages bigint NOT NULL DEFAULT 0 CHECK (spam_messages >= 0),
  ham_messages bigint NOT NULL DEFAULT 0 CHECK (ham_messages >= 0),
  last_seen bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, token_hash)
);

-- table plugin_experimental_spam_bootstraps
CREATE TABLE plugin_experimental_spam_bootstraps (
  user_id bigint PRIMARY KEY,
  status text COLLATE "C" NOT NULL CHECK (status IN ('idle', 'running', 'complete', 'failed', 'cancelled')),
  cutoff_at bigint NOT NULL DEFAULT 0,
  candidate_spam bigint NOT NULL DEFAULT 0 CHECK (candidate_spam >= 0),
  candidate_ham bigint NOT NULL DEFAULT 0 CHECK (candidate_ham >= 0),
  examined bigint NOT NULL DEFAULT 0 CHECK (examined >= 0),
  accepted_spam bigint NOT NULL DEFAULT 0 CHECK (accepted_spam >= 0),
  accepted_ham bigint NOT NULL DEFAULT 0 CHECK (accepted_ham >= 0),
  rejected bigint NOT NULL DEFAULT 0 CHECK (rejected >= 0),
  current_mailbox text COLLATE "C" NOT NULL DEFAULT '',
  last_error text COLLATE "C" NOT NULL DEFAULT '',
  started_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL,
  completed_at bigint NOT NULL DEFAULT 0
);

-- table plugin_experimental_spam_classifications
CREATE TABLE plugin_experimental_spam_classifications (
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  model_version text COLLATE "C" NOT NULL,
  base_probability double precision NOT NULL,
  labeled_neighbor_probability double precision NOT NULL DEFAULT 0.5,
  labeled_neighbor_count bigint NOT NULL DEFAULT 0,
  recent_read_support double precision NOT NULL DEFAULT 0,
  final_probability double precision NOT NULL,
  risk_band text COLLATE "C" NOT NULL CHECK (risk_band IN ('low', 'medium', 'high')),
  content_coverage text COLLATE "C" NOT NULL DEFAULT 'metadata',
  explanation_json text COLLATE "C" NOT NULL DEFAULT '{}',
  classified_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, message_id)
);

-- table plugin_experimental_spam_feedback
CREATE TABLE plugin_experimental_spam_feedback (
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL CHECK (label IN ('spam', 'ham')),
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY (user_id, message_id)
);

-- table plugin_experimental_spam_pending_move_labels
CREATE TABLE plugin_experimental_spam_pending_move_labels (
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  identity_key text COLLATE "C" NOT NULL,
  label text COLLATE "C" NOT NULL CHECK (label IN ('spam', 'ham')),
  source_mailbox_id bigint NOT NULL,
  destination_mailbox_id bigint NOT NULL,
  created_at bigint NOT NULL,
  expires_at bigint NOT NULL,
  PRIMARY KEY (user_id, account_id, identity_key)
);

-- table plugin_gravatar_cache
CREATE TABLE plugin_gravatar_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  email_hash text COLLATE "C" NOT NULL,
  content_type text COLLATE "C" NOT NULL DEFAULT '',
  image bytea,
  status text COLLATE "C" NOT NULL DEFAULT '',
  error text COLLATE "C" NOT NULL DEFAULT '',
  fetched_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, email_hash)
);

-- table plugin_language_messages
CREATE TABLE plugin_language_messages (
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  language_code text COLLATE "C" NOT NULL,
  detected_at bigint NOT NULL,
  PRIMARY KEY(user_id, message_id)
);

-- table plugin_mail_filter_evaluations
CREATE TABLE plugin_mail_filter_evaluations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  rule_id bigint NOT NULL,
  message_id bigint NOT NULL,
  account_id bigint NOT NULL DEFAULT 0,
  mailbox_id bigint NOT NULL DEFAULT 0,
  phase text COLLATE "C" NOT NULL DEFAULT '',
  status text COLLATE "C" NOT NULL DEFAULT '',
  matched bigint NOT NULL DEFAULT 0,
  due_at bigint NOT NULL DEFAULT 0,
  evaluated_at bigint NOT NULL DEFAULT 0,
  terms_json text COLLATE "C" NOT NULL DEFAULT '[]',
  fields_json text COLLATE "C" NOT NULL DEFAULT '[]',
  actions_json text COLLATE "C" NOT NULL DEFAULT '{}',
  error text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL
);

-- table plugin_mail_filter_forwarders
CREATE TABLE plugin_mail_filter_forwarders (
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  forwarder_id text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY(user_id, account_id)
);

-- table plugin_mail_filter_rule_accounts
CREATE TABLE plugin_mail_filter_rule_accounts (
  rule_id bigint NOT NULL,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  PRIMARY KEY(rule_id, account_id)
);

-- table plugin_mail_filter_rules
CREATE TABLE plugin_mail_filter_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text COLLATE "C" NOT NULL DEFAULT '',
  query text COLLATE "C" NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  scope_mode text COLLATE "C" NOT NULL DEFAULT 'all_accounts',
  actions_json text COLLATE "C" NOT NULL DEFAULT '{}',
  position bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table plugin_mail_mcp_grants
CREATE TABLE plugin_mail_mcp_grants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  client_id text COLLATE "C" NOT NULL DEFAULT '',
  scope text COLLATE "C" NOT NULL DEFAULT '',
  redirect_uri text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  last_used_at bigint NOT NULL DEFAULT 0,
  revoked_at bigint NOT NULL DEFAULT 0
);

-- table plugin_migrations
CREATE TABLE plugin_migrations (
  plugin_id text COLLATE "C" NOT NULL,
  migration_id text COLLATE "C" NOT NULL,
  applied_at bigint NOT NULL,
  app_version text COLLATE "C" NOT NULL DEFAULT '',
  checksum text COLLATE "C" NOT NULL,
  PRIMARY KEY(plugin_id, migration_id)
);

-- table plugin_one_click_unsubscribe_sends
CREATE TABLE plugin_one_click_unsubscribe_sends (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  sender text COLLATE "C" NOT NULL DEFAULT '',
  unsubscribe_url text COLLATE "C" NOT NULL,
  sent_at bigint NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE(user_id, message_id, unsubscribe_url)
);

-- table plugin_remote_image_blocklist_rules
CREATE TABLE plugin_remote_image_blocklist_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern text COLLATE "C" NOT NULL UNIQUE,
  enabled bigint NOT NULL DEFAULT 1,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table plugin_remote_imap_sync_messages
CREATE TABLE plugin_remote_imap_sync_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  routine_id bigint NOT NULL,
  source_uidvalidity bigint NOT NULL,
  source_uid bigint NOT NULL,
  source_fingerprint text COLLATE "C" NOT NULL,
  marker text COLLATE "C" NOT NULL,
  destination_uid bigint NOT NULL DEFAULT 0,
  status text COLLATE "C" NOT NULL DEFAULT 'transferred',
  copied_at bigint NOT NULL,
  UNIQUE(user_id, routine_id, source_uidvalidity, source_uid)
);

-- table plugin_remote_imap_sync_provenance
CREATE TABLE plugin_remote_imap_sync_provenance (
  user_id bigint NOT NULL,
  destination_account_id bigint NOT NULL,
  destination_mailbox_id bigint NOT NULL,
  destination_uidvalidity bigint NOT NULL CHECK (destination_uidvalidity > 0),
  destination_uid bigint NOT NULL CHECK (destination_uid > 0),
  destination_sha256 text COLLATE "C" NOT NULL CHECK ( length(destination_sha256) = 64 AND destination_sha256 ~ '^[0-9a-f]*$' ),
  synced_at bigint NOT NULL CHECK (synced_at > 0),
  PRIMARY KEY (user_id, destination_account_id, destination_mailbox_id, destination_uidvalidity, destination_uid)
);

-- table plugin_remote_imap_sync_routines
CREATE TABLE plugin_remote_imap_sync_routines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  name text COLLATE "C" NOT NULL DEFAULT '',
  enabled bigint NOT NULL DEFAULT 1,
  source_provider text COLLATE "C" NOT NULL DEFAULT 'custom',
  source_host text COLLATE "C" NOT NULL,
  source_port bigint NOT NULL DEFAULT 993,
  source_username text COLLATE "C" NOT NULL,
  encrypted_source_password text COLLATE "C" NOT NULL,
  source_use_tls bigint NOT NULL DEFAULT 1,
  source_mailbox text COLLATE "C" NOT NULL DEFAULT 'INBOX',
  destination_account_id bigint NOT NULL,
  destination_mailbox_id bigint NOT NULL,
  after_date bigint NOT NULL DEFAULT 0,
  marker_secret text COLLATE "C" NOT NULL,
  source_uidvalidity bigint NOT NULL DEFAULT 0,
  last_source_uid bigint NOT NULL DEFAULT 0,
  state text COLLATE "C" NOT NULL DEFAULT 'paused',
  last_error text COLLATE "C" NOT NULL DEFAULT '',
  last_started_at bigint NOT NULL DEFAULT 0,
  last_completed_at bigint NOT NULL DEFAULT 0,
  last_activity_at bigint NOT NULL DEFAULT 0,
  next_retry_at bigint NOT NULL DEFAULT 0,
  transferred_total bigint NOT NULL DEFAULT 0,
  skipped_total bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(id, user_id),
  UNIQUE(user_id, source_host, source_port, source_username, source_mailbox, destination_account_id, destination_mailbox_id)
);

-- table plugin_remote_imap_sync_runs
CREATE TABLE plugin_remote_imap_sync_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  routine_id bigint NOT NULL,
  trigger text COLLATE "C" NOT NULL DEFAULT 'scheduled',
  status text COLLATE "C" NOT NULL DEFAULT 'queued',
  scanned bigint NOT NULL DEFAULT 0,
  transferred bigint NOT NULL DEFAULT 0,
  skipped bigint NOT NULL DEFAULT 0,
  current_uid bigint NOT NULL DEFAULT 0,
  error text COLLATE "C" NOT NULL DEFAULT '',
  started_at bigint NOT NULL DEFAULT 0,
  completed_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL
);

-- table plugin_settings
CREATE TABLE plugin_settings (
  id text COLLATE "C" PRIMARY KEY,
  name text COLLATE "C" NOT NULL,
  description text COLLATE "C" NOT NULL DEFAULT '',
  enabled bigint NOT NULL,
  enabled_by_default bigint NOT NULL,
  heavy bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table plugin_trusted_image_sources
CREATE TABLE plugin_trusted_image_sources (
  user_id bigint NOT NULL,
  sender text COLLATE "C" NOT NULL,
  created_at bigint NOT NULL,
  PRIMARY KEY(user_id, sender)
);

-- table remote_image_cache
CREATE TABLE remote_image_cache (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  url_hash text COLLATE "C" NOT NULL,
  url text COLLATE "C" NOT NULL,
  blob_id bigint NOT NULL DEFAULT 0,
  blob_path text COLLATE "C" NOT NULL DEFAULT '',
  content_type text COLLATE "C" NOT NULL DEFAULT '',
  size bigint NOT NULL DEFAULT 0,
  status text COLLATE "C" NOT NULL,
  error text COLLATE "C" NOT NULL DEFAULT '',
  fetched_at bigint NOT NULL DEFAULT 0,
  expires_at bigint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  UNIQUE(user_id, url_hash)
);

-- table schema_migrations
CREATE TABLE schema_migrations (
  scope text COLLATE "C" NOT NULL,
  version text COLLATE "C" NOT NULL,
  applied_at bigint NOT NULL,
  checksum text COLLATE "C" NOT NULL,
  PRIMARY KEY(scope, version)
);

-- table sender_read_stats
CREATE TABLE sender_read_stats (
  user_id bigint NOT NULL,
  sender text COLLATE "C" NOT NULL,
  read_count bigint NOT NULL DEFAULT 0,
  total_count bigint NOT NULL DEFAULT 0,
  boost double precision NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL,
  PRIMARY KEY(user_id, sender)
);

-- table sessions
CREATE TABLE sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  token_hash text COLLATE "C" NOT NULL UNIQUE,
  expires_at bigint NOT NULL,
  created_at bigint NOT NULL,
  last_seen_at bigint NOT NULL
);

-- table smtp_accounts
CREATE TABLE smtp_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  label text COLLATE "C" NOT NULL DEFAULT '',
  host text COLLATE "C" NOT NULL,
  port bigint NOT NULL DEFAULT 587,
  username text COLLATE "C" NOT NULL DEFAULT '',
  encrypted_password text COLLATE "C" NOT NULL DEFAULT '',
  use_tls bigint NOT NULL DEFAULT 1,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  auth_type text COLLATE "C" NOT NULL DEFAULT 'password',
  google_connection_id bigint NOT NULL DEFAULT 0
);

-- table snooze_reminder_events
CREATE TABLE snooze_reminder_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  message_id bigint NOT NULL,
  snooze_generation bigint NOT NULL,
  from_addr text COLLATE "C" NOT NULL DEFAULT '',
  subject text COLLATE "C" NOT NULL DEFAULT '',
  due_at bigint NOT NULL,
  created_at bigint NOT NULL,
  UNIQUE(user_id, message_id, snooze_generation)
);

-- table swipe_archive_mailboxes
CREATE TABLE swipe_archive_mailboxes (
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  mailbox_id bigint NOT NULL,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  PRIMARY KEY(user_id, account_id),
  UNIQUE(user_id, mailbox_id)
);

-- table swipe_preferences
CREATE TABLE swipe_preferences (
  user_id bigint PRIMARY KEY,
  left_action text COLLATE "C" NOT NULL DEFAULT 'snooze' CHECK(left_action IN ('trash', 'archive', 'snooze', 'mark_read', 'mark_unread')),
  left_snooze_preset text COLLATE "C" NOT NULL DEFAULT 'tomorrow' CHECK(left_snooze_preset IN ('later_today', 'tomorrow', 'next_week')),
  right_action text COLLATE "C" NOT NULL DEFAULT 'mark_read' CHECK(right_action IN ('trash', 'archive', 'snooze', 'mark_read', 'mark_unread')),
  right_snooze_preset text COLLATE "C" NOT NULL DEFAULT 'tomorrow' CHECK(right_snooze_preset IN ('later_today', 'tomorrow', 'next_week')),
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table sync_runs
CREATE TABLE sync_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  account_id bigint NOT NULL,
  status text COLLATE "C" NOT NULL,
  started_at bigint NOT NULL,
  finished_at bigint NOT NULL DEFAULT 0,
  updated_at bigint NOT NULL DEFAULT 0,
  messages_seen bigint NOT NULL DEFAULT 0,
  messages_stored bigint NOT NULL DEFAULT 0,
  messages_skipped bigint NOT NULL DEFAULT 0,
  new_messages bigint NOT NULL DEFAULT 0,
  latest_new_from text COLLATE "C" NOT NULL DEFAULT '',
  latest_new_subject text COLLATE "C" NOT NULL DEFAULT '',
  messages_total bigint NOT NULL DEFAULT 0,
  mailboxes_done bigint NOT NULL DEFAULT 0,
  mailboxes_total bigint NOT NULL DEFAULT 0,
  current_mailbox text COLLATE "C" NOT NULL DEFAULT '',
  current_uid bigint NOT NULL DEFAULT 0,
  error text COLLATE "C" NOT NULL DEFAULT '',
  latest_new_message_id bigint NOT NULL DEFAULT 0
);

-- table system_settings
CREATE TABLE system_settings (
  key text COLLATE "C" PRIMARY KEY,
  value text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL
);

-- table users
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text COLLATE "C" NOT NULL UNIQUE,
  name text COLLATE "C" NOT NULL,
  password_hash text COLLATE "C" NOT NULL,
  is_admin bigint NOT NULL DEFAULT 0,
  date_locale text COLLATE "C" NOT NULL DEFAULT '',
  date_format text COLLATE "C" NOT NULL DEFAULT 'mdy',
  theme text COLLATE "C" NOT NULL DEFAULT 'classic',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  search_preset text COLLATE "C" NOT NULL DEFAULT 'balanced',
  search_recency_bias text COLLATE "C" NOT NULL DEFAULT 'normal',
  search_fuzzy text COLLATE "C" NOT NULL DEFAULT 'balanced',
  search_sender_boost bigint NOT NULL DEFAULT 1,
  search_attachment_weight text COLLATE "C" NOT NULL DEFAULT 'normal',
  search_compact_splitting bigint NOT NULL DEFAULT 1,
  search_sender_history text COLLATE "C" NOT NULL DEFAULT 'normal',
  search_contact_boost text COLLATE "C" NOT NULL DEFAULT 'normal',
  backup_email text COLLATE "C" NOT NULL DEFAULT ''
);

-- table web_push_subscriptions
CREATE TABLE web_push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  endpoint text COLLATE "C" NOT NULL,
  p256dh text COLLATE "C" NOT NULL,
  auth text COLLATE "C" NOT NULL,
  user_agent text COLLATE "C" NOT NULL DEFAULT '',
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  last_seen_at bigint NOT NULL,
  last_new_mail_event_id bigint NOT NULL DEFAULT 0,
  last_snooze_reminder_event_id bigint NOT NULL DEFAULT 0,
  UNIQUE(user_id, endpoint)
);

-- index idx_attachments_user_message
CREATE INDEX idx_attachments_user_message ON attachments (user_id, message_id);

-- index idx_blob_cleanup_queue_user
CREATE INDEX idx_blob_cleanup_queue_user ON blob_cleanup_queue (user_id, id);

-- index idx_blobs_user
CREATE INDEX idx_blobs_user ON blobs (user_id);

-- index idx_calendar_events_external
CREATE UNIQUE INDEX idx_calendar_events_external ON calendar_events (user_id, calendar_id, external_id);

-- index idx_calendar_events_window
CREATE INDEX idx_calendar_events_window ON calendar_events (user_id, calendar_id, start_at);

-- index idx_calendars_google
CREATE UNIQUE INDEX idx_calendars_google ON calendars (user_id, google_connection_id, google_calendar_id);

-- index idx_contact_addresses_user_contact
CREATE INDEX idx_contact_addresses_user_contact ON contact_addresses (user_id, contact_id);

-- index idx_contact_emails_user_address
CREATE INDEX idx_contact_emails_user_address ON contact_emails (user_id, normalized_email);

-- index idx_contact_emails_user_contact
CREATE INDEX idx_contact_emails_user_contact ON contact_emails (user_id, contact_id);

-- index idx_contact_icons_user_contact
CREATE INDEX idx_contact_icons_user_contact ON contact_icons (user_id, contact_id);

-- index idx_contact_pgp_public_keys_user_contact
CREATE INDEX idx_contact_pgp_public_keys_user_contact ON contact_pgp_public_keys (user_id, contact_id);

-- index idx_contact_pgp_public_keys_user_email
CREATE INDEX idx_contact_pgp_public_keys_user_email ON contact_pgp_public_keys (user_id, normalized_email, is_preferred DESC);

-- index idx_contact_phones_user_contact
CREATE INDEX idx_contact_phones_user_contact ON contact_phones (user_id, contact_id);

-- index idx_contact_urls_user_contact
CREATE INDEX idx_contact_urls_user_contact ON contact_urls (user_id, contact_id);

-- index idx_contacts_google_external
CREATE UNIQUE INDEX idx_contacts_google_external ON contacts (user_id, google_connection_id, external_id) WHERE external_id <> '';

-- index idx_contacts_user_me
CREATE INDEX idx_contacts_user_me ON contacts (user_id, is_me, is_primary);

-- index idx_contacts_user_name
CREATE INDEX idx_contacts_user_name ON contacts (user_id, lower(display_name));

-- index idx_expunged_message_fingerprints_canonical
CREATE INDEX idx_expunged_message_fingerprints_canonical ON expunged_message_fingerprints (user_id, account_id, canonical_sha256, expires_at, id) WHERE consumed_at = 0 AND canonical_sha256 <> '';

-- index idx_expunged_message_fingerprints_expiry
CREATE INDEX idx_expunged_message_fingerprints_expiry ON expunged_message_fingerprints (user_id, expires_at);

-- index idx_expunged_message_fingerprints_message_id
CREATE INDEX idx_expunged_message_fingerprints_message_id ON expunged_message_fingerprints (user_id, account_id, message_id_hash, internal_date_unix, message_size, expires_at, id) WHERE consumed_at = 0 AND message_id_hash <> '';

-- index idx_expunged_message_fingerprints_raw
CREATE INDEX idx_expunged_message_fingerprints_raw ON expunged_message_fingerprints (user_id, account_id, raw_sha256, expires_at, id) WHERE consumed_at = 0 AND raw_sha256 <> '';

-- index idx_identity_pgp_private_keys_user_identity
CREATE INDEX idx_identity_pgp_private_keys_user_identity ON identity_pgp_private_keys (user_id, identity_id);

-- index idx_mail_accounts_user
CREATE INDEX idx_mail_accounts_user ON mail_accounts (user_id);

-- index idx_mail_accounts_user_account
CREATE UNIQUE INDEX idx_mail_accounts_user_account ON mail_accounts (user_id, id);

-- index idx_mail_identities_smtp
CREATE INDEX idx_mail_identities_smtp ON mail_identities (user_id, smtp_account_id);

-- index idx_mail_identities_user
CREATE INDEX idx_mail_identities_user ON mail_identities (user_id);

-- index idx_mailbox_generation_blob_cleanup_scope
CREATE INDEX idx_mailbox_generation_blob_cleanup_scope ON mailbox_generation_blob_cleanup (user_id, account_id, mailbox_id, id);

-- index idx_mailbox_generation_rebuild_canonical
CREATE INDEX idx_mailbox_generation_rebuild_canonical ON mailbox_generation_rebuild_messages (user_id, account_id, mailbox_id, target_uid_validity, canonical_sha256, id) WHERE canonical_sha256 <> '';

-- index idx_mailbox_generation_rebuild_message_id
CREATE INDEX idx_mailbox_generation_rebuild_message_id ON mailbox_generation_rebuild_messages (user_id, account_id, mailbox_id, target_uid_validity, message_id_hash, internal_date_unix, message_size, id) WHERE message_id_hash <> '';

-- index idx_mailbox_generation_rebuild_raw
CREATE INDEX idx_mailbox_generation_rebuild_raw ON mailbox_generation_rebuild_messages (user_id, account_id, mailbox_id, target_uid_validity, raw_sha256, id) WHERE raw_sha256 <> '';

-- index idx_mailbox_generation_rebuild_target
CREATE INDEX idx_mailbox_generation_rebuild_target ON mailbox_generation_rebuild_messages (user_id, account_id, mailbox_id, target_uid_validity, id);

-- index idx_mailboxes_user_account_mailbox
CREATE UNIQUE INDEX idx_mailboxes_user_account_mailbox ON mailboxes (user_id, account_id, id);

-- index idx_mailboxes_user_all_mail
CREATE INDEX idx_mailboxes_user_all_mail ON mailboxes (user_id, show_in_all_mail, id);

-- index idx_message_snoozes_user_due
CREATE INDEX idx_message_snoozes_user_due ON message_snoozes (user_id, reminded_at, snoozed_until);

-- index idx_message_transfers_active_copy_operation
CREATE UNIQUE INDEX idx_message_transfers_active_copy_operation ON message_transfers (user_id, source_account_id, source_mailbox_id, source_uid, source_uid_validity, destination_account_id, destination_mailbox_id) WHERE source_mailbox_id IS NOT NULL AND operation_kind = 'copy' AND state IN ('pending', 'succeeded');

-- index idx_message_transfers_active_move_source
CREATE UNIQUE INDEX idx_message_transfers_active_move_source ON message_transfers (user_id, source_account_id, source_mailbox_id, source_uid, source_uid_validity) WHERE source_mailbox_id IS NOT NULL AND operation_kind = 'move' AND state IN ('pending', 'succeeded');

-- index idx_message_transfers_canonical
CREATE INDEX idx_message_transfers_canonical ON message_transfers (user_id, destination_account_id, destination_mailbox_id, canonical_sha256, expires_at, id) WHERE state = 'succeeded' AND canonical_sha256 <> '';

-- index idx_message_transfers_destination_uid
CREATE INDEX idx_message_transfers_destination_uid ON message_transfers (user_id, destination_account_id, destination_mailbox_id, destination_uid, destination_uid_validity, expires_at, id) WHERE state = 'succeeded' AND destination_uid > 0;

-- index idx_message_transfers_expiry
CREATE INDEX idx_message_transfers_expiry ON message_transfers (user_id, expires_at, state);

-- index idx_message_transfers_message_id
CREATE INDEX idx_message_transfers_message_id ON message_transfers (user_id, destination_account_id, destination_mailbox_id, message_id_hash, internal_date_unix, message_size, expires_at, id) WHERE state = 'succeeded' AND message_id_hash <> '';

-- index idx_message_transfers_raw
CREATE INDEX idx_message_transfers_raw ON message_transfers (user_id, destination_account_id, destination_mailbox_id, raw_sha256, expires_at, id) WHERE state = 'succeeded' AND raw_sha256 <> '';

-- index idx_messages_category_pending
CREATE INDEX idx_messages_category_pending ON messages (user_id, id) WHERE category = '';

-- index idx_messages_thread_headers_checked
CREATE INDEX idx_messages_thread_headers_checked ON messages (thread_headers_checked_at, id);

-- index idx_messages_user_category_date
CREATE INDEX idx_messages_user_category_date ON messages (user_id, category, date_unix);

-- index idx_messages_user_date
CREATE INDEX idx_messages_user_date ON messages (user_id, date_unix DESC, id DESC);

-- index idx_messages_user_duplicate_of
CREATE INDEX idx_messages_user_duplicate_of ON messages (user_id, duplicate_of_message_id) WHERE duplicate_of_message_id <> 0;

-- index idx_messages_user_encrypted
CREATE INDEX idx_messages_user_encrypted ON messages (user_id, is_encrypted);

-- index idx_messages_user_from_read
CREATE INDEX idx_messages_user_from_read ON messages (user_id, from_addr, is_read);

-- index idx_messages_user_id_id
CREATE UNIQUE INDEX idx_messages_user_id_id ON messages (user_id, id);

-- index idx_messages_user_mailbox_read
CREATE INDEX idx_messages_user_mailbox_read ON messages (user_id, mailbox_id, is_read);

-- index idx_messages_user_mailbox_search_committed
CREATE INDEX idx_messages_user_mailbox_search_committed ON messages (user_id, mailbox_id, id) WHERE attachment_indexed_at > 0;

-- index idx_messages_user_mailbox_thread
CREATE INDEX idx_messages_user_mailbox_thread ON messages (user_id, mailbox_id, thread_key, date_unix, id);

-- index idx_messages_user_mailbox_thread_latest
CREATE INDEX idx_messages_user_mailbox_thread_latest ON messages (user_id, mailbox_id, thread_key, date_unix DESC, id DESC);

-- index idx_messages_user_message_id_header
CREATE INDEX idx_messages_user_message_id_header ON messages (user_id, message_id_header, account_id) WHERE message_id_header <> '';

-- index idx_messages_user_sender_address
CREATE INDEX idx_messages_user_sender_address ON messages (user_id, sender_address);

-- index idx_messages_user_signed
CREATE INDEX idx_messages_user_signed ON messages (user_id, is_signed);

-- index idx_messages_user_starred
CREATE INDEX idx_messages_user_starred ON messages (user_id, is_starred, date_unix DESC, id DESC);

-- index idx_messages_user_thread
CREATE INDEX idx_messages_user_thread ON messages (user_id, thread_key, date_unix, id);

-- index idx_messages_user_thread_latest
CREATE INDEX idx_messages_user_thread_latest ON messages (user_id, thread_key, date_unix DESC, id DESC);

-- index idx_new_mail_events_user_id
CREATE INDEX idx_new_mail_events_user_id ON new_mail_events (user_id, id DESC);

-- index idx_password_reset_tokens_hash
CREATE INDEX idx_password_reset_tokens_hash ON password_reset_tokens (token_hash);

-- index idx_password_reset_tokens_user
CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id, expires_at);

-- index idx_pending_inbox_arrivals_due
CREATE INDEX idx_pending_inbox_arrivals_due ON pending_inbox_arrivals (user_id, account_id, classification, available_at, id);

-- index idx_pending_inbox_arrivals_run
CREATE INDEX idx_pending_inbox_arrivals_run ON pending_inbox_arrivals (user_id, sync_run_id, classification);

-- index idx_pending_move_notifications_consumed
CREATE INDEX idx_pending_move_notifications_consumed ON pending_move_notifications (user_id, consumed_message_id, expires_at) WHERE consumed_message_id IS NOT NULL;

-- index idx_pending_move_notifications_expiry
CREATE INDEX idx_pending_move_notifications_expiry ON pending_move_notifications (user_id, expires_at);

-- index idx_pending_move_notifications_lookup
CREATE INDEX idx_pending_move_notifications_lookup ON pending_move_notifications (user_id, account_id, destination_mailbox_id, raw_sha256, expires_at, id) WHERE consumed_message_id IS NULL;

-- index idx_plugin_bimi_brand_icons_user_domain
CREATE INDEX idx_plugin_bimi_brand_icons_user_domain ON plugin_bimi_brand_icons (user_id, domain);

-- index idx_plugin_experimental_spam_bayes_labels_effective
CREATE INDEX idx_plugin_experimental_spam_bayes_labels_effective ON plugin_experimental_spam_bayes_labels (user_id, message_fingerprint, source, updated_at, origin_key);

-- index idx_plugin_experimental_spam_bayes_labels_expiry
CREATE INDEX idx_plugin_experimental_spam_bayes_labels_expiry ON plugin_experimental_spam_bayes_labels (user_id, source, updated_at, origin_key);

-- index idx_plugin_experimental_spam_bayes_labels_message
CREATE UNIQUE INDEX idx_plugin_experimental_spam_bayes_labels_message ON plugin_experimental_spam_bayes_labels (user_id, message_id) WHERE source = 'explicit' AND message_id IS NOT NULL;

-- index idx_plugin_experimental_spam_bayes_learn_tokens_hash
CREATE INDEX idx_plugin_experimental_spam_bayes_learn_tokens_hash ON plugin_experimental_spam_bayes_learn_tokens (user_id, token_hash, message_fingerprint);

-- index idx_plugin_experimental_spam_bayes_learns_expiry
CREATE INDEX idx_plugin_experimental_spam_bayes_learns_expiry ON plugin_experimental_spam_bayes_learns (user_id, updated_at, message_id);

-- index idx_plugin_experimental_spam_bayes_learns_fingerprint
CREATE INDEX idx_plugin_experimental_spam_bayes_learns_fingerprint ON plugin_experimental_spam_bayes_learns (user_id, message_fingerprint, message_id);

-- index idx_plugin_experimental_spam_classifications_user_band
CREATE INDEX idx_plugin_experimental_spam_classifications_user_band ON plugin_experimental_spam_classifications (user_id, risk_band, message_id);

-- index idx_plugin_experimental_spam_feedback_user_label_recent
CREATE INDEX idx_plugin_experimental_spam_feedback_user_label_recent ON plugin_experimental_spam_feedback (user_id, label, updated_at DESC, message_id DESC);

-- index idx_plugin_experimental_spam_pending_move_labels_expiry
CREATE INDEX idx_plugin_experimental_spam_pending_move_labels_expiry ON plugin_experimental_spam_pending_move_labels (user_id, expires_at);

-- index idx_plugin_gravatar_cache_user_hash
CREATE INDEX idx_plugin_gravatar_cache_user_hash ON plugin_gravatar_cache (user_id, email_hash);

-- index idx_plugin_language_messages_user_language
CREATE INDEX idx_plugin_language_messages_user_language ON plugin_language_messages (user_id, language_code);

-- index idx_plugin_mail_filter_evaluations_due
CREATE INDEX idx_plugin_mail_filter_evaluations_due ON plugin_mail_filter_evaluations (status, due_at);

-- index idx_plugin_mail_filter_evaluations_message
CREATE INDEX idx_plugin_mail_filter_evaluations_message ON plugin_mail_filter_evaluations (user_id, message_id, id);

-- index idx_plugin_mail_filter_evaluations_user_rule_time
CREATE INDEX idx_plugin_mail_filter_evaluations_user_rule_time ON plugin_mail_filter_evaluations (user_id, rule_id, evaluated_at DESC, id DESC);

-- index idx_plugin_mail_filter_rule_accounts_user_account
CREATE INDEX idx_plugin_mail_filter_rule_accounts_user_account ON plugin_mail_filter_rule_accounts (user_id, account_id);

-- index idx_plugin_mail_filter_rules_user_enabled
CREATE INDEX idx_plugin_mail_filter_rules_user_enabled ON plugin_mail_filter_rules (user_id, enabled, position, id);

-- index idx_plugin_mail_mcp_grants_user_active
CREATE INDEX idx_plugin_mail_mcp_grants_user_active ON plugin_mail_mcp_grants (user_id, revoked_at, id);

-- index idx_plugin_mail_mcp_grants_user_client_scope
CREATE UNIQUE INDEX idx_plugin_mail_mcp_grants_user_client_scope ON plugin_mail_mcp_grants (user_id, client_id, scope);

-- index idx_plugin_one_click_unsubscribe_user_message
CREATE INDEX idx_plugin_one_click_unsubscribe_user_message ON plugin_one_click_unsubscribe_sends (user_id, message_id, sent_at DESC);

-- index idx_plugin_one_click_unsubscribe_user_url
CREATE INDEX idx_plugin_one_click_unsubscribe_user_url ON plugin_one_click_unsubscribe_sends (user_id, unsubscribe_url, sent_at DESC);

-- index idx_plugin_remote_imap_sync_messages_user_fingerprint
CREATE INDEX idx_plugin_remote_imap_sync_messages_user_fingerprint ON plugin_remote_imap_sync_messages (user_id, routine_id, source_fingerprint);

-- index idx_plugin_remote_imap_sync_messages_user_marker
CREATE INDEX idx_plugin_remote_imap_sync_messages_user_marker ON plugin_remote_imap_sync_messages (user_id, routine_id, marker);

-- index idx_plugin_remote_imap_sync_routines_user_enabled
CREATE INDEX idx_plugin_remote_imap_sync_routines_user_enabled ON plugin_remote_imap_sync_routines (user_id, enabled, id);

-- index idx_plugin_remote_imap_sync_runs_user_routine_time
CREATE INDEX idx_plugin_remote_imap_sync_runs_user_routine_time ON plugin_remote_imap_sync_runs (user_id, routine_id, id DESC);

-- index idx_remote_image_cache_user_status
CREATE INDEX idx_remote_image_cache_user_status ON remote_image_cache (user_id, status, expires_at);

-- index idx_sender_read_stats_user_boost
CREATE INDEX idx_sender_read_stats_user_boost ON sender_read_stats (user_id, boost DESC, read_count DESC, sender);

-- index idx_sessions_token_hash
CREATE INDEX idx_sessions_token_hash ON sessions (token_hash);

-- index idx_smtp_accounts_user
CREATE INDEX idx_smtp_accounts_user ON smtp_accounts (user_id);

-- index idx_snooze_reminder_events_user_id
CREATE INDEX idx_snooze_reminder_events_user_id ON snooze_reminder_events (user_id, id DESC);

-- index idx_swipe_archive_mailboxes_user_mailbox
CREATE INDEX idx_swipe_archive_mailboxes_user_mailbox ON swipe_archive_mailboxes (user_id, mailbox_id);

-- index idx_sync_runs_user
CREATE INDEX idx_sync_runs_user ON sync_runs (user_id, started_at DESC);

-- index idx_web_push_subscriptions_user_updated
CREATE INDEX idx_web_push_subscriptions_user_updated ON web_push_subscriptions (user_id, updated_at DESC);

-- foreign keys attachments
ALTER TABLE attachments ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD FOREIGN KEY (blob_id) REFERENCES blobs(id) ON DELETE RESTRICT;

-- foreign keys blob_cleanup_queue
ALTER TABLE blob_cleanup_queue ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys blobs
ALTER TABLE blobs ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys calendar_events
ALTER TABLE calendar_events ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE calendar_events ADD FOREIGN KEY (calendar_id) REFERENCES calendars(id) ON DELETE CASCADE;

-- foreign keys calendars
ALTER TABLE calendars ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys category_sender_overrides
ALTER TABLE category_sender_overrides ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys contact_addresses
ALTER TABLE contact_addresses ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_addresses ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;

-- foreign keys contact_emails
ALTER TABLE contact_emails ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_emails ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;

-- foreign keys contact_icons
ALTER TABLE contact_icons ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_icons ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE contact_icons ADD FOREIGN KEY (blob_id) REFERENCES blobs(id) ON DELETE RESTRICT;

-- foreign keys contact_pgp_public_keys
ALTER TABLE contact_pgp_public_keys ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_pgp_public_keys ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;

-- foreign keys contact_phones
ALTER TABLE contact_phones ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_phones ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;

-- foreign keys contact_urls
ALTER TABLE contact_urls ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE contact_urls ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;

-- foreign keys contacts
ALTER TABLE contacts ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys expunged_message_fingerprints
ALTER TABLE expunged_message_fingerprints ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE expunged_message_fingerprints ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE expunged_message_fingerprints ADD FOREIGN KEY (source_mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;
ALTER TABLE expunged_message_fingerprints ADD FOREIGN KEY (consumed_message_id) REFERENCES messages(id) ON DELETE SET NULL;

-- foreign keys google_calendar_sync
ALTER TABLE google_calendar_sync ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys google_connections
ALTER TABLE google_connections ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys google_people_sync
ALTER TABLE google_people_sync ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys identity_pgp_private_keys
ALTER TABLE identity_pgp_private_keys ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE identity_pgp_private_keys ADD FOREIGN KEY (identity_id) REFERENCES mail_identities(id) ON DELETE CASCADE;

-- foreign keys locations
ALTER TABLE locations ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE locations ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE locations ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;

-- foreign keys mail_accounts
ALTER TABLE mail_accounts ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys mail_identities
ALTER TABLE mail_identities ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mail_identities ADD FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE mail_identities ADD FOREIGN KEY (contact_email_id) REFERENCES contact_emails(id) ON DELETE CASCADE;

-- foreign keys mailbox_generation_blob_cleanup
ALTER TABLE mailbox_generation_blob_cleanup ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_blob_cleanup ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_blob_cleanup ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;

-- foreign keys mailbox_generation_rebuild_inbox_arrivals
ALTER TABLE mailbox_generation_rebuild_inbox_arrivals ADD FOREIGN KEY (rebuild_message_id) REFERENCES mailbox_generation_rebuild_messages(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_inbox_arrivals ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_inbox_arrivals ADD FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE SET NULL;

-- foreign keys mailbox_generation_rebuild_messages
ALTER TABLE mailbox_generation_rebuild_messages ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_messages ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_messages ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;

-- foreign keys mailbox_generation_rebuild_snooze_events
ALTER TABLE mailbox_generation_rebuild_snooze_events ADD FOREIGN KEY (rebuild_message_id) REFERENCES mailbox_generation_rebuild_messages(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_snooze_events ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys mailbox_generation_rebuild_unsubscribe_sends
ALTER TABLE mailbox_generation_rebuild_unsubscribe_sends ADD FOREIGN KEY (rebuild_message_id) REFERENCES mailbox_generation_rebuild_messages(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuild_unsubscribe_sends ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys mailbox_generation_rebuilds
ALTER TABLE mailbox_generation_rebuilds ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuilds ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE mailbox_generation_rebuilds ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;

-- foreign keys mailboxes
ALTER TABLE mailboxes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE mailboxes ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;

-- foreign keys message_snoozes
ALTER TABLE message_snoozes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE message_snoozes ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys message_transfers
ALTER TABLE message_transfers ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE message_transfers ADD FOREIGN KEY (source_account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE message_transfers ADD FOREIGN KEY (destination_account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE message_transfers ADD FOREIGN KEY (source_mailbox_id) REFERENCES mailboxes(id) ON DELETE SET NULL;
ALTER TABLE message_transfers ADD FOREIGN KEY (destination_mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;
ALTER TABLE message_transfers ADD FOREIGN KEY (source_message_id) REFERENCES messages(id) ON DELETE SET NULL;
ALTER TABLE message_transfers ADD FOREIGN KEY (consumed_message_id) REFERENCES messages(id) ON DELETE SET NULL;

-- foreign keys messages
ALTER TABLE messages ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE messages ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE messages ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;
ALTER TABLE messages ADD FOREIGN KEY (blob_id) REFERENCES blobs(id) ON DELETE RESTRICT;

-- foreign keys new_mail_events
ALTER TABLE new_mail_events ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE new_mail_events ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys password_reset_tokens
ALTER TABLE password_reset_tokens ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys pending_inbox_arrivals
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE SET NULL;
ALTER TABLE pending_inbox_arrivals ADD FOREIGN KEY (event_id) REFERENCES new_mail_events(id) ON DELETE SET NULL;

-- foreign keys pending_move_notifications
ALTER TABLE pending_move_notifications ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE pending_move_notifications ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;
ALTER TABLE pending_move_notifications ADD FOREIGN KEY (destination_mailbox_id) REFERENCES mailboxes(id) ON DELETE CASCADE;
ALTER TABLE pending_move_notifications ADD FOREIGN KEY (consumed_message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys plugin_bimi_brand_icons
ALTER TABLE plugin_bimi_brand_icons ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_backfills
ALTER TABLE plugin_experimental_spam_backfills ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_documents
ALTER TABLE plugin_experimental_spam_bayes_documents ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_labels
ALTER TABLE plugin_experimental_spam_bayes_labels ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_experimental_spam_bayes_labels ADD FOREIGN KEY (user_id, message_fingerprint) REFERENCES plugin_experimental_spam_bayes_documents(user_id, message_fingerprint) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_learn_tokens
ALTER TABLE plugin_experimental_spam_bayes_learn_tokens ADD FOREIGN KEY (user_id, message_fingerprint) REFERENCES plugin_experimental_spam_bayes_documents(user_id, message_fingerprint) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_learns
ALTER TABLE plugin_experimental_spam_bayes_learns ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_experimental_spam_bayes_learns ADD FOREIGN KEY (user_id, message_fingerprint) REFERENCES plugin_experimental_spam_bayes_documents(user_id, message_fingerprint) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_state
ALTER TABLE plugin_experimental_spam_bayes_state ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bayes_tokens
ALTER TABLE plugin_experimental_spam_bayes_tokens ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_bootstraps
ALTER TABLE plugin_experimental_spam_bootstraps ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_classifications
ALTER TABLE plugin_experimental_spam_classifications ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_experimental_spam_classifications ADD FOREIGN KEY (user_id, message_id) REFERENCES messages(user_id, id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_feedback
ALTER TABLE plugin_experimental_spam_feedback ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_experimental_spam_feedback ADD FOREIGN KEY (user_id, message_id) REFERENCES messages(user_id, id) ON DELETE CASCADE;

-- foreign keys plugin_experimental_spam_pending_move_labels
ALTER TABLE plugin_experimental_spam_pending_move_labels ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_gravatar_cache
ALTER TABLE plugin_gravatar_cache ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_language_messages
ALTER TABLE plugin_language_messages ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_language_messages ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys plugin_mail_filter_evaluations
ALTER TABLE plugin_mail_filter_evaluations ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_mail_filter_evaluations ADD FOREIGN KEY (rule_id) REFERENCES plugin_mail_filter_rules(id) ON DELETE CASCADE;

-- foreign keys plugin_mail_filter_forwarders
ALTER TABLE plugin_mail_filter_forwarders ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_mail_filter_forwarders ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;

-- foreign keys plugin_mail_filter_rule_accounts
ALTER TABLE plugin_mail_filter_rule_accounts ADD FOREIGN KEY (rule_id) REFERENCES plugin_mail_filter_rules(id) ON DELETE CASCADE;
ALTER TABLE plugin_mail_filter_rule_accounts ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_mail_filter_rule_accounts ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;

-- foreign keys plugin_mail_filter_rules
ALTER TABLE plugin_mail_filter_rules ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_mail_mcp_grants
ALTER TABLE plugin_mail_mcp_grants ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_one_click_unsubscribe_sends
ALTER TABLE plugin_one_click_unsubscribe_sends ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_one_click_unsubscribe_sends ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys plugin_remote_imap_sync_messages
ALTER TABLE plugin_remote_imap_sync_messages ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_remote_imap_sync_messages ADD FOREIGN KEY(routine_id, user_id) REFERENCES plugin_remote_imap_sync_routines(id, user_id) ON DELETE CASCADE;

-- foreign keys plugin_remote_imap_sync_provenance
ALTER TABLE plugin_remote_imap_sync_provenance ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_remote_imap_sync_routines
ALTER TABLE plugin_remote_imap_sync_routines ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys plugin_remote_imap_sync_runs
ALTER TABLE plugin_remote_imap_sync_runs ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE plugin_remote_imap_sync_runs ADD FOREIGN KEY(routine_id, user_id) REFERENCES plugin_remote_imap_sync_routines(id, user_id) ON DELETE CASCADE;

-- foreign keys plugin_trusted_image_sources
ALTER TABLE plugin_trusted_image_sources ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys remote_image_cache
ALTER TABLE remote_image_cache ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys sender_read_stats
ALTER TABLE sender_read_stats ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys sessions
ALTER TABLE sessions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys smtp_accounts
ALTER TABLE smtp_accounts ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys snooze_reminder_events
ALTER TABLE snooze_reminder_events ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE snooze_reminder_events ADD FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;

-- foreign keys swipe_archive_mailboxes
ALTER TABLE swipe_archive_mailboxes ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE swipe_archive_mailboxes ADD FOREIGN KEY(user_id, account_id) REFERENCES mail_accounts(user_id, id) ON DELETE CASCADE;
ALTER TABLE swipe_archive_mailboxes ADD FOREIGN KEY(user_id, account_id, mailbox_id) REFERENCES mailboxes(user_id, account_id, id) ON DELETE CASCADE;

-- foreign keys swipe_preferences
ALTER TABLE swipe_preferences ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- foreign keys sync_runs
ALTER TABLE sync_runs ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE sync_runs ADD FOREIGN KEY (account_id) REFERENCES mail_accounts(id) ON DELETE CASCADE;

-- foreign keys web_push_subscriptions
ALTER TABLE web_push_subscriptions ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- trigger messages_clear_duplicate_pointer
CREATE FUNCTION messages_clear_duplicate_pointer() RETURNS trigger AS $$
BEGIN
  -- Mirrors the SQLite trigger: when a message that others point at as their
  -- duplicate original is deleted, clear those pointers instead of leaving
  -- them dangling. AGENTS.md keeps this in SQL because reconciliation, folder
  -- purges, and account deletion all delete messages by different paths.
  UPDATE messages AS m SET duplicate_of_message_id = 0
  FROM deleted AS d
  WHERE m.user_id = d.user_id AND m.duplicate_of_message_id = d.id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER messages_clear_duplicate_pointer
AFTER DELETE ON messages
REFERENCING OLD TABLE AS deleted
FOR EACH STATEMENT EXECUTE FUNCTION messages_clear_duplicate_pointer();
