package pgschema

import (
	"strings"
	"testing"
)

func translateOne(t *testing.T, kind, name, ddl string) []Object {
	t.Helper()
	objects, err := Translate([]SQLiteObject{{Kind: kind, Name: name, SQL: ddl}})
	if err != nil {
		t.Fatal(err)
	}
	return objects
}

func TestTranslateColumnTypes(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		count INTEGER NOT NULL DEFAULT 0,
		label TEXT NOT NULL DEFAULT '',
		image BLOB,
		boost REAL NOT NULL DEFAULT 0
	)`)
	got := objects[0].SQL
	for _, want := range []string{
		"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
		"count bigint NOT NULL DEFAULT 0",
		`label text COLLATE "C" NOT NULL DEFAULT ''`,
		"image bytea",
		"boost double precision NOT NULL DEFAULT 0",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
}

// TestTranslateColumnNamedLikeAConstraint is the regression test for a column
// called "checksum" being mistaken for a CHECK constraint and passed through
// untranslated.
func TestTranslateColumnNamedLikeAConstraint(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (
		checksum TEXT NOT NULL,
		uniqueness TEXT NOT NULL,
		constraint_note TEXT NOT NULL,
		primary_contact TEXT NOT NULL
	)`)
	got := objects[0].SQL
	for _, column := range []string{"checksum", "uniqueness", "constraint_note", "primary_contact"} {
		if !strings.Contains(got, column+` text COLLATE "C" NOT NULL`) {
			t.Errorf("column %s was not translated:\n%s", column, got)
		}
	}
}

func TestTranslateKeepsTableConstraints(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (
		a INTEGER NOT NULL,
		b INTEGER NOT NULL,
		PRIMARY KEY(a, b),
		UNIQUE(b)
	)`)
	got := objects[0].SQL
	if !strings.Contains(got, "PRIMARY KEY(a, b)") || !strings.Contains(got, "UNIQUE(b)") {
		t.Errorf("table constraints lost:\n%s", got)
	}
}

// TestTranslateSplitsForeignKeys pins the phase split: no REFERENCES may
// remain in a CREATE TABLE, because the unique indexes composite keys need do
// not exist yet at that point.
func TestTranslateSplitsForeignKeys(t *testing.T) {
	objects, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
		account_id INTEGER NOT NULL,
		FOREIGN KEY(user_id, account_id) REFERENCES mail_accounts(user_id, id) ON DELETE CASCADE
	)`}})
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 2 {
		t.Fatalf("got %d objects, want a table plus its foreign keys", len(objects))
	}
	table, keys := objects[0], objects[1]
	if strings.Contains(table.SQL, "REFERENCES") {
		t.Errorf("table still carries a foreign key:\n%s", table.SQL)
	}
	if !strings.Contains(table.SQL, "user_id bigint NOT NULL") {
		t.Errorf("column lost its type when the reference was split off:\n%s", table.SQL)
	}
	if keys.Kind != ForeignKeysKind {
		t.Fatalf("second object is %q", keys.Kind)
	}
	for _, want := range []string{
		"ALTER TABLE t ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;",
		"ALTER TABLE t ADD FOREIGN KEY(user_id, account_id) REFERENCES mail_accounts(user_id, id) ON DELETE CASCADE;",
	} {
		if !strings.Contains(keys.SQL, want) {
			t.Errorf("missing %q in:\n%s", want, keys.SQL)
		}
	}
}

// TestTranslateForeignKeysComeAfterIndexes is the ordering the composite keys
// depend on.
func TestTranslateForeignKeysComeAfterIndexes(t *testing.T) {
	objects, err := Translate([]SQLiteObject{
		{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (a INTEGER NOT NULL REFERENCES u(id))`},
		{Kind: IndexKind, Name: "idx_u", SQL: `CREATE UNIQUE INDEX idx_u ON u(id)`},
	})
	if err != nil {
		t.Fatal(err)
	}
	var indexAt, keysAt = -1, -1
	for i, object := range objects {
		switch object.Kind {
		case IndexKind:
			indexAt = i
		case ForeignKeysKind:
			keysAt = i
		}
	}
	if indexAt < 0 || keysAt < 0 || indexAt > keysAt {
		t.Fatalf("index at %d, foreign keys at %d; keys must come last", indexAt, keysAt)
	}
}

func TestTranslateIndexes(t *testing.T) {
	cases := []struct {
		name string
		ddl  string
		want string
	}{
		{"plain", `CREATE INDEX i ON t(a, b)`, "CREATE INDEX i ON t (a, b);"},
		{"unique", `CREATE UNIQUE INDEX i ON t(a)`, "CREATE UNIQUE INDEX i ON t (a);"},
		{"partial", `CREATE UNIQUE INDEX i ON t(a, b) WHERE b <> ''`, "CREATE UNIQUE INDEX i ON t (a, b) WHERE b <> '';"},
		{"nocase", `CREATE INDEX i ON t(user_id, name COLLATE NOCASE)`, "CREATE INDEX i ON t (user_id, lower(name));"},
		{"binary", `CREATE INDEX i ON t(sha COLLATE BINARY)`, "CREATE INDEX i ON t (sha);"},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			objects := translateOne(t, IndexKind, "i", test.ddl)
			if objects[0].SQL != test.want {
				t.Errorf("got  %s\nwant %s", objects[0].SQL, test.want)
			}
		})
	}
}

// TestTranslateStripsLineComments covers the inline documentation the store's
// migrations carry: folding a comment into the following line would swallow
// the column after it.
func TestTranslateStripsLineComments(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (
		-- The address is display data and can change.
		email TEXT NOT NULL,
		-- Another note, with a comma, that must not split anything.
		name TEXT NOT NULL
	)`)
	got := objects[0].SQL
	if strings.Contains(got, "--") {
		t.Errorf("comment survived translation:\n%s", got)
	}
	for _, column := range []string{"email", "name"} {
		if !strings.Contains(got, column+` text COLLATE "C" NOT NULL`) {
			t.Errorf("column %s missing:\n%s", column, got)
		}
	}
}

// TestTranslateKeepsLiteralsIntact is the regression test for a REFERENCES
// inside a quoted DEFAULT being extracted as a foreign key, which corrupted
// the default and invented a constraint out of its text.
func TestTranslateKeepsLiteralsIntact(t *testing.T) {
	objects, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		note TEXT NOT NULL DEFAULT 'REFERENCES u(id)',
		spaced TEXT NOT NULL DEFAULT 'a  b',
		quoted TEXT NOT NULL DEFAULT 'it''s here',
		binary_note TEXT NOT NULL DEFAULT 'literal COLLATE BINARY value',
		nocase_note TEXT NOT NULL DEFAULT 'literal COLLATE NOCASE value'
	)`}})
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 1 {
		t.Fatalf("got %d objects, want the table alone with no invented foreign key", len(objects))
	}
	got := objects[0].SQL
	for _, want := range []string{
		`note text COLLATE "C" NOT NULL DEFAULT 'REFERENCES u(id)'`,
		`spaced text COLLATE "C" NOT NULL DEFAULT 'a  b'`,
		`quoted text COLLATE "C" NOT NULL DEFAULT 'it''s here'`,
		`binary_note text COLLATE "C" NOT NULL DEFAULT 'literal COLLATE BINARY value'`,
		`nocase_note text COLLATE "C" NOT NULL DEFAULT 'literal COLLATE NOCASE value'`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("literal was rewritten; missing %q in:\n%s", want, got)
		}
	}
}

// TestTranslateStripsRealCollateOutsideLiterals is the other half of the
// literal test: an actual column collation still has to be removed, and an
// actual NOCASE index column still has to become lower().
func TestTranslateStripsRealCollateOutsideLiterals(t *testing.T) {
	objects := translateOne(t, TableKind, "t",
		`CREATE TABLE t (sha TEXT NOT NULL DEFAULT '' COLLATE BINARY)`)
	if strings.Contains(objects[0].SQL, "COLLATE BINARY") {
		t.Errorf("a real COLLATE BINARY was not removed:\n%s", objects[0].SQL)
	}
	if !strings.Contains(objects[0].SQL, `sha text COLLATE "C" NOT NULL DEFAULT ''`) {
		t.Errorf("column lost its shape:\n%s", objects[0].SQL)
	}
	index := translateOne(t, IndexKind, "i",
		`CREATE INDEX i ON t(name COLLATE NOCASE) WHERE note <> 'COLLATE NOCASE'`)
	if index[0].SQL != `CREATE INDEX i ON t (lower(name)) WHERE note <> 'COLLATE NOCASE';` {
		t.Errorf("index collation handling changed a literal or missed a real one:\n%s", index[0].SQL)
	}
}

// TestTranslateRejectsColumnLevelNoCase is the regression test for a
// COLLATE NOCASE that survives outside an index column: it produced invalid
// PostgreSQL (a duplicate COLLATE clause naming a collation PostgreSQL does
// not have) instead of failing the build.
func TestTranslateRejectsColumnLevelNoCase(t *testing.T) {
	if _, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t",
		SQL: `CREATE TABLE t (name TEXT NOT NULL COLLATE NOCASE)`}}); err == nil {
		t.Error("a column-level COLLATE NOCASE was accepted")
	}
	if _, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		name TEXT NOT NULL,
		UNIQUE(name COLLATE NOCASE)
	)`}}); err == nil {
		t.Error("a table-constraint COLLATE NOCASE was accepted")
	}
	// The index rewrite this restriction carves out an exception for must
	// keep working.
	objects := translateOne(t, IndexKind, "i", `CREATE INDEX i ON t(name COLLATE NOCASE)`)
	if objects[0].SQL != "CREATE INDEX i ON t (lower(name));" {
		t.Errorf("the supported index rewrite regressed: %s", objects[0].SQL)
	}
}

// TestTranslateSplitsNamedForeignKeys covers the branch-order bug: a named
// constraint matched the generic table-constraint test first and stayed
// inline, defeating the phase split.
func TestTranslateSplitsNamedForeignKeys(t *testing.T) {
	objects, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		a INTEGER NOT NULL,
		CONSTRAINT fk_a FOREIGN KEY (a) REFERENCES u(id) ON DELETE CASCADE
	)`}})
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 2 {
		t.Fatalf("got %d objects, want the table plus its foreign keys", len(objects))
	}
	if strings.Contains(objects[0].SQL, "FOREIGN KEY") {
		t.Errorf("named foreign key stayed inline:\n%s", objects[0].SQL)
	}
	if !strings.Contains(objects[1].SQL, "ALTER TABLE t ADD CONSTRAINT fk_a FOREIGN KEY (a) REFERENCES u(id) ON DELETE CASCADE;") {
		t.Errorf("named foreign key not emitted as ALTER TABLE:\n%s", objects[1].SQL)
	}
}

// TestTranslateSplitsReferencesWithoutColumnList covers SQLite's implicit
// primary-key form, which the extractor used to leave inline.
func TestTranslateSplitsReferencesWithoutColumnList(t *testing.T) {
	objects, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE
	)`}})
	if err != nil {
		t.Fatal(err)
	}
	if len(objects) != 2 {
		t.Fatalf("got %d objects, want the table plus its foreign keys", len(objects))
	}
	if strings.Contains(objects[0].SQL, "REFERENCES") {
		t.Errorf("reference without a column list stayed inline:\n%s", objects[0].SQL)
	}
}

// TestTranslateStripsWithoutRowid covers the SQLite storage-form suffix, and
// pins that any other trailing clause is refused instead of dropped.
func TestTranslateStripsWithoutRowid(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (a INTEGER NOT NULL, PRIMARY KEY (a)) WITHOUT ROWID`)
	if strings.Contains(strings.ToUpper(objects[0].SQL), "WITHOUT ROWID") {
		t.Errorf("WITHOUT ROWID survived:\n%s", objects[0].SQL)
	}
	if _, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (a INTEGER) STRICT`}}); err == nil {
		t.Error("an unknown trailing clause was accepted")
	}
}

// TestTranslateRejectsUntranslatedSQLiteExpressions keeps CHECK constraints
// from silently losing their meaning: a dropped constraint is one the
// database stops enforcing.
func TestTranslateRejectsUntranslatedSQLiteExpressions(t *testing.T) {
	if _, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (
		a TEXT NOT NULL CHECK (a NOT GLOB '*[^0-9]*')
	)`}}); err == nil {
		t.Error("an untranslated GLOB was accepted")
	}
	if _, err := Translate([]SQLiteObject{{Kind: IndexKind, Name: "i", SQL: `CREATE INDEX i ON t(a) WHERE a > strftime('%s', 'now')`}}); err == nil {
		t.Error("an untranslated strftime was accepted")
	}
}

// TestTranslateIdentityAcceptsExplicitIDs pins the identity form: the
// migration tool copies ids verbatim, which GENERATED ALWAYS would reject.
func TestTranslateIdentityAcceptsExplicitIDs(t *testing.T) {
	objects := translateOne(t, TableKind, "t", `CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT)`)
	if !strings.Contains(objects[0].SQL, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Errorf("identity column is not insertable with an explicit id:\n%s", objects[0].SQL)
	}
}

// TestTranslateTriggerPinsItsSource is the drift guard: matching on the name
// alone would keep emitting a stale translation after the SQLite body
// changed, leaving the golden file byte-identical.
func TestTranslateTriggerPinsItsSource(t *testing.T) {
	changed := strings.Replace(duplicatePointerTriggerSQLite, "= 0", "= -1", 1)
	if _, err := Translate([]SQLiteObject{{Kind: TriggerKind, Name: "messages_clear_duplicate_pointer", SQL: changed}}); err == nil {
		t.Error("a changed trigger body was accepted with the old translation")
	}
	if _, err := Translate([]SQLiteObject{{Kind: TriggerKind, Name: "messages_clear_duplicate_pointer", SQL: duplicatePointerTriggerSQLite}}); err != nil {
		t.Errorf("the pinned trigger body was rejected: %v", err)
	}
}

// TestTranslateSortsByName keeps the golden file independent of SQLite's
// physical page layout, which shifts when a migration rebuilds a table.
func TestTranslateSortsByName(t *testing.T) {
	objects, err := Translate([]SQLiteObject{
		{Kind: TableKind, Name: "zebra", SQL: `CREATE TABLE zebra (a INTEGER)`},
		{Kind: TableKind, Name: "alpha", SQL: `CREATE TABLE alpha (a INTEGER)`},
	})
	if err != nil {
		t.Fatal(err)
	}
	if objects[0].Name != "alpha" || objects[1].Name != "zebra" {
		t.Errorf("tables not name-sorted: %s, %s", objects[0].Name, objects[1].Name)
	}
}

func TestTranslateRejectsUnknownTypeAndTrigger(t *testing.T) {
	if _, err := Translate([]SQLiteObject{{Kind: TableKind, Name: "t", SQL: `CREATE TABLE t (when_at TIMESTAMP NOT NULL)`}}); err == nil {
		t.Error("an unmapped column type was accepted")
	}
	if _, err := Translate([]SQLiteObject{{Kind: TriggerKind, Name: "something_new", SQL: `CREATE TRIGGER something_new AFTER INSERT ON t BEGIN SELECT 1; END`}}); err == nil {
		t.Error("an untranslated trigger was accepted")
	}
}

func TestTranslateRejectsUnsupportedKind(t *testing.T) {
	if _, err := Translate([]SQLiteObject{{Kind: "view", Name: "v", SQL: `CREATE VIEW v AS SELECT 1`}}); err == nil {
		t.Error("a view was accepted; views need a deliberate decision")
	}
}

func TestSplitTopLevelIgnoresCommasInParensAndStrings(t *testing.T) {
	parts, err := splitTopLevel(`a INTEGER, b TEXT DEFAULT 'x,y', PRIMARY KEY(a, b)`)
	if err != nil {
		t.Fatal(err)
	}
	if len(parts) != 3 {
		t.Fatalf("got %d parts: %q", len(parts), parts)
	}
}
