CREATE TABLE IF NOT EXISTS plugin_webdav_archive_targets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 1,
  base_url TEXT NOT NULL,
  username TEXT NOT NULL DEFAULT '',
  encrypted_password TEXT NOT NULL DEFAULT '',
  watch_mailbox_id INTEGER NOT NULL DEFAULT 0,
  content_types TEXT NOT NULL DEFAULT 'audio/',
  path_template TEXT NOT NULL DEFAULT '{yyyy}/{mm}/{filename}',
  include_inline INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  last_success_at INTEGER NOT NULL DEFAULT 0,
  uploaded_total INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE(id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_plugin_webdav_archive_targets_user_enabled
  ON plugin_webdav_archive_targets(user_id, enabled, id);

CREATE INDEX IF NOT EXISTS idx_plugin_webdav_archive_targets_watch
  ON plugin_webdav_archive_targets(user_id, watch_mailbox_id, enabled);

CREATE TABLE IF NOT EXISTS plugin_webdav_archive_uploads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_id INTEGER NOT NULL,
  message_id INTEGER NOT NULL,
  attachment_id INTEGER NOT NULL DEFAULT 0,
  filename TEXT NOT NULL DEFAULT '',
  content_type TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0,
  remote_path TEXT NOT NULL DEFAULT '',
  content_hash TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,
  next_attempt_at INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '',
  from_addr TEXT NOT NULL DEFAULT '',
  message_date INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  completed_at INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(target_id, user_id) REFERENCES plugin_webdav_archive_targets(id, user_id) ON DELETE CASCADE,
  UNIQUE(user_id, target_id, message_id, attachment_id)
);

CREATE INDEX IF NOT EXISTS idx_plugin_webdav_archive_uploads_due
  ON plugin_webdav_archive_uploads(status, next_attempt_at, id);

CREATE INDEX IF NOT EXISTS idx_plugin_webdav_archive_uploads_user_time
  ON plugin_webdav_archive_uploads(user_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_plugin_webdav_archive_uploads_user_hash
  ON plugin_webdav_archive_uploads(user_id, target_id, content_hash);
